language: android
jdk: openjdk12
node_js: "10.15"

android:
  components:
    - build-tools-28.0.3
    - android-28

before_install:
  - npm install -g react-native-cli

script:
  - cd android
  - ./gradlew clean
  - ./gradlew assemblDebug